name: Docs

on:
  push:
    branches: [ master, 'dev/*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # update archive links
        sudo apt update

        # See test.yml for description of the following deps
        sudo apt-get -y install xvfb libgtk-3-dev freeglut3-dev portaudio19-dev libpulse-dev pulseaudio libsdl2-dev

        python -m pip install --upgrade pip wheel

        # Install wxPython wheels since they are distribution-specific and therefore not on PyPI
        # See: https://wxpython.org/pages/downloads/index.html
        pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython

        pip install .
    - name: Build docs
      run: |
        cd doc && make html
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/html
 
